version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    ports:
      - 3000:3000
    env_file:
      -  ../envs/common-frontend.env
    environment:
      NEXT_PUBLIC_API_HOST: devnet.${DOMAIN:?DOMAIN is required}
      NEXT_PUBLIC_STATS_API_HOST: https://devnet-stats.${DOMAIN:?DOMAIN is required}
      NEXT_PUBLIC_NETWORK_RPC_URL: https://devnet-rpc.${DOMAIN:?DOMAIN is required}
      NEXT_PUBLIC_APP_HOST: devnet.${DOMAIN:?DOMAIN is required}
      NEXT_PUBLIC_VISUALIZE_API_HOST: https://devnet-visual.${DOMAIN:?DOMAIN is required}
      NEXT_PUBLIC_FEATURED_NETWORKS: https://devnet.${DOMAIN:?DOMAIN is required}/featured_networks.json
